### ISSUE TITLE
[功能建议] 音讯路径以及手动查询功能

### ISSUE THREAD

**Issue by kevinfis** [ISouthRain/dict-line#3]
偶然看到这个包, 用过后觉得好用, 用到目前碰到两个状况有两个建议:
1. 在第178这个位置   (audio-file (concat dict-line-audio-root-dir first-letter "/" dict-line-word ".mp3")) 建议加斜线改为 (concat dict-line-audio-root-dir "/" first-letter "/" dict-line-word ".mp3")) , 因为dict-line-audio-root-dir 设成 "/tmp/audio/" 有了斜线,  那 "/tmp/audio//A" 还是可开启; 不过如果dict-line-audio-root-dir 设成 "/tmp/audio" 那concat后就会变成 "/tmp/audioA" 无法开启此路径, 就没有声音了, 算是给使用者容错.
2. 建议 defun dict-line--get-dict-async 那能够加入 (interactive) 手动来让设定绑定键执行. 主要目的是一篇文章若有7成以上字不熟, 目前这种idle跳出查询结果很好用; 然而如果是只有 4成不到, 连续查询就有点干扰阅读了, 特别是一般来说冠词、代名词、甚至be动词其实可以省略不查的(我相信会用emacs的人英语再差,用字典久了也不用查这些字). 不过跳过特定字根据使用者不同需求, 牵涉到的过滤字典工程量可能太大, 所以让 dict-line-mode 关闭时可以设定热键用来临时查询几个不懂的, 会更简单通用些.

**Comment by ISouthRain** [comment]
@kevinfis 
Ha~~~
谢谢你的建议, 我感觉你说的都挺不错的...
1. 关于路径问题, 谢谢你的提醒, 我已经更改了...
2. 支持手动调用问题, 由于我的 posframe 使用了固定不自动消失的方法,  所以不是太好, 我之后会添加个参数让它自动消失, 但我已添加了 interactive

最后, 谢谢你的喜欢.
如果你还其他问题或想法, 我希望你完全可以使用 Pull requests 给我, 我欢迎所有人..

**Comment by kevinfis** [comment]
坦白elisp还在学,加上讲Github还用不熟, 有机会再试操作看看. 
第二点当时在忙著找无法发音问题过程中, 我忘记临时改了dict-line-mode,  注解掉 progn 里面的 (run-with-idle-timer dict-line-idle-time t #'dict-line--get-dict-async), 就取名dict-line-manual-mode当作手动的模式来用, 提这篇时忘了这动作, 如果改版有参数可以关掉就更好了. 这篇就是那时在看.el档过程中一直跳出查询结果才会顺便提出来的.
最后再次谢谢这个包, 现在用就很好用了, 目前也只想到临时想改变框颜色, 颜色定义放在函数dict-line--posframe里面, 所以在customize-group 没法直接改, 可以加进去更好.

**Comment by ISouthRain** [comment]
@kevinfis 
如果你需要修改显示样式, 我建议你新建一个函数, 并让变量 dict-line-display 指定你新建的函数, dict-line-display 本来就是为了不同显示样式提供的选项..

**Comment by kevinfis** [comment]
elisp还不够熟, 其实你的包我也不能全部都看懂, 谢谢提点处理机制,  这样我就知道怎么改边框颜色了.
