### ISSUE TITLE
[讨论]兩個語音使用上的問題

### ISSUE THREAD

**Issue by kevinfis** [ISouthRain/dict-line#4]
1. 因为播放语音时总感觉发音被截断, 查了发现发音这段  run-at-time "1 sec" 只有设一秒,
    目前语音包无法一秒念完像是單字 repositories , 至少要设1.5秒,
    顺便试了下 pneumonoultramicroscopicsilicovolcanoconiosis 要4秒才唸的完,
    不过我想大部份单字没有这么长, 有的单字目前字典还没有列进去, 像 supercalifragilisticexpialidocious 就找不到,
    所以不知道要建议改几秒,
    当初定1秒是不是目的是快速念完单字?  是那样好像也不一定要设到4秒?
2. 使用過程发现大写字没有发音, 变量dict-line-word可能需要补个downcase转成小写, 因为音訊檔案都是小写的:
(audio-file (concat dict-line-audio-root-dir "/" first-letter "/" (downcase dict-line-word) ".mp3"))

**Comment by ISouthRain** [comment]
## 关于第一个问题:
首先我需要向你抱歉, 这是我的设计问题.  
因为如果不在1秒或其他时间 关闭/杀掉 这个播放音频 pid, 会发现一种奇怪的问题, 播放音频文件时有时只播放一次音频, 但有时它会一直重复无限次播放这个音频文件, 所以我给定了个时间将它kill掉, 这个我没有找到其他办法解决这个问题, 所以我将它一段时间主动 kill 掉, 以防止出现一直重复播放问题   
也不是 mplayer 的原因, 我有试过添加了只播放一次的参数给mplayer, 但还是没有解决这个问题

## 关于第二个问题
我不是很明白你的问题, 你说的大写是怎么个大写呢?   
以我这边为例:
单词: Play, play, PLAY
无论何种形式都能正常播放发音

**Comment by kevinfis** [comment]
关于第一个问题,
我有发现部份档名有重复的(数量不少),例如单字 abetting 有两个文档,
在emacs看是:
 abetting\015.mp3   (用gnome-shell看,档名是 abetting$'\r'.mp3)
 abetting.mp3
除了档名外, 文档大小还有声音内容都一样.
档名这个\015好像是ASCII控制符号,
提供参考, 不知道这个可不可能造成这个现象?

这个问题我把时间改大再测试更久一段时间,看看会不会出现你碰到的这个现象.
刚刚短暂试过(我播放用的是mpv), 查了一会没碰到重覆播放音频不停的.


第二个问题 我之前查开头大写的 Difference 不会播放声音.
另外我试过 emacs -q ,用use-pacakage 加载dict-line.el, (git下载的.el,没有任何修改)
;;这是use-package的dict-line设置
(use-package dict-line
  :diminish
  (dict-line-mode "🗺️")
  :ensure nil
  :load-path "~/.emacs.d/site-lisp/dict-line/"
  :custom
  (dict-line-audio-play-program "mpv")
  (dict-line-audio t)
  (dict-line-audio-root-dir "/home/user/.dict/pronunciations_en/audio/")
  (dict-line-dict-directory "/home/user/.dict/vscode_english_chinese_dictionary/src/词典数据")
  (dict-line-dict-personal-file "/home/user/.dict/mydict.ts")
  (dict-line-display #'dict-line--posframe)
  :config
  (global-set-key (kbd "Ņ") 'dict-line--get-dict-async)
  )
也是无法 播放有大写的 Play PLAY
这就奇怪了, 我用archlinux, 编译版本 emacs 29.3.50, 应该没差才对.
反而我的系统要加上 (downcase dict-line-word) 才能播放有大写的单字.

**Comment by ISouthRain** [comment]
> 反而我的系统要加上 (downcase dict-line-word) 才能播放有大写的单字.

我想我知道为什么了, 大概是因为 Linux 和 Windows 区分与不区分文件名大小写问题了, 谢谢你的反馈, 我已将这个补丁添加了.

**Comment by ISouthRain** [comment]
> 这个问题我把时间改大再测试更久一段时间,看看会不会出现你碰到的这个现象.
> 刚刚短暂试过(我播放用的是mpv), 查了一会没碰到重覆播放音频不停的.

期待你后续的反馈, 希望有改进, 到时还要麻烦你提供一下解决方案. 哈哈哈

**Comment by kevinfis** [comment]
哈哈, 有幫的上忙就好.
dict-line蠻好用的, 我也希望能查得到原因, 讓他更好用, 至於要提出解決方案, 那我也要持續加強一下elisp了才行了, 目前有點拼喔~~

**Comment by ISouthRain** [comment]
@kevinfis 
`dict-line` 现在经过了重构, 建议更新, 现在速度比以前更快了, 更省CPU资源.
